services:
  - type: web
    name: text-to-avatar-video-api
    runtime: docker
    plan: free
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: HEYGEN_API_KEY
        sync: false
      - key: HEYGEN_DEFAULT_AVATAR_ID
        sync: false
      - key: HEYGEN_DEFAULT_VOICE_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health
